# Use this file for encrypted user/password information.
# Unencrypted values may be used in this file using standard yaml syntax
# Encrypted values must be enclosed in ![] within the quotes.
db:
  password: '![gOm0V2CzVPuH5FAJby2h8Q==]'
